// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/mongo"
)

// NewMockMongoDatabaseService creates a new instance of MockMongoDatabaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoDatabaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoDatabaseService {
	mock := &MockMongoDatabaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoDatabaseService is an autogenerated mock type for the MongoDatabaseService type
type MockMongoDatabaseService struct {
	mock.Mock
}

type MockMongoDatabaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoDatabaseService) EXPECT() *MockMongoDatabaseService_Expecter {
	return &MockMongoDatabaseService_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMongoDatabaseService
func (_mock *MockMongoDatabaseService) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMongoDatabaseService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMongoDatabaseService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMongoDatabaseService_Expecter) Close(ctx interface{}) *MockMongoDatabaseService_Close_Call {
	return &MockMongoDatabaseService_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockMongoDatabaseService_Close_Call) Run(run func(ctx context.Context)) *MockMongoDatabaseService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoDatabaseService_Close_Call) Return(err error) *MockMongoDatabaseService_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMongoDatabaseService_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockMongoDatabaseService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollection provides a mock function for the type MockMongoDatabaseService
func (_mock *MockMongoDatabaseService) GetCollection(name string) *mongo.Collection {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 *mongo.Collection
	if returnFunc, ok := ret.Get(0).(func(string) *mongo.Collection); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Collection)
		}
	}
	return r0
}

// MockMongoDatabaseService_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockMongoDatabaseService_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
//   - name string
func (_e *MockMongoDatabaseService_Expecter) GetCollection(name interface{}) *MockMongoDatabaseService_GetCollection_Call {
	return &MockMongoDatabaseService_GetCollection_Call{Call: _e.mock.On("GetCollection", name)}
}

func (_c *MockMongoDatabaseService_GetCollection_Call) Run(run func(name string)) *MockMongoDatabaseService_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoDatabaseService_GetCollection_Call) Return(collection *mongo.Collection) *MockMongoDatabaseService_GetCollection_Call {
	_c.Call.Return(collection)
	return _c
}

func (_c *MockMongoDatabaseService_GetCollection_Call) RunAndReturn(run func(name string) *mongo.Collection) *MockMongoDatabaseService_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSQLDatabaseService creates a new instance of MockSQLDatabaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSQLDatabaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSQLDatabaseService {
	mock := &MockSQLDatabaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSQLDatabaseService is an autogenerated mock type for the SQLDatabaseService type
type MockSQLDatabaseService struct {
	mock.Mock
}

type MockSQLDatabaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSQLDatabaseService) EXPECT() *MockSQLDatabaseService_Expecter {
	return &MockSQLDatabaseService_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockSQLDatabaseService
func (_mock *MockSQLDatabaseService) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSQLDatabaseService_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSQLDatabaseService_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSQLDatabaseService_Expecter) Close() *MockSQLDatabaseService_Close_Call {
	return &MockSQLDatabaseService_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSQLDatabaseService_Close_Call) Run(run func()) *MockSQLDatabaseService_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSQLDatabaseService_Close_Call) Return(err error) *MockSQLDatabaseService_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSQLDatabaseService_Close_Call) RunAndReturn(run func() error) *MockSQLDatabaseService_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Rebind provides a mock function for the type MockSQLDatabaseService
func (_mock *MockSQLDatabaseService) Rebind(query string) string {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Rebind")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(query)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSQLDatabaseService_Rebind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rebind'
type MockSQLDatabaseService_Rebind_Call struct {
	*mock.Call
}

// Rebind is a helper method to define mock.On call
//   - query string
func (_e *MockSQLDatabaseService_Expecter) Rebind(query interface{}) *MockSQLDatabaseService_Rebind_Call {
	return &MockSQLDatabaseService_Rebind_Call{Call: _e.mock.On("Rebind", query)}
}

func (_c *MockSQLDatabaseService_Rebind_Call) Run(run func(query string)) *MockSQLDatabaseService_Rebind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSQLDatabaseService_Rebind_Call) Return(s string) *MockSQLDatabaseService_Rebind_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSQLDatabaseService_Rebind_Call) RunAndReturn(run func(query string) string) *MockSQLDatabaseService_Rebind_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type MockSQLDatabaseService
func (_mock *MockSQLDatabaseService) Select(dest interface{}, query string, args ...interface{}) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(dest, query, args)
	} else {
		tmpRet = _mock.Called(dest, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, ...interface{}) error); ok {
		r0 = returnFunc(dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSQLDatabaseService_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockSQLDatabaseService_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - dest interface{}
//   - query string
//   - args ...interface{}
func (_e *MockSQLDatabaseService_Expecter) Select(dest interface{}, query interface{}, args ...interface{}) *MockSQLDatabaseService_Select_Call {
	return &MockSQLDatabaseService_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{dest, query}, args...)...)}
}

func (_c *MockSQLDatabaseService_Select_Call) Run(run func(dest interface{}, query string, args ...interface{})) *MockSQLDatabaseService_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSQLDatabaseService_Select_Call) Return(err error) *MockSQLDatabaseService_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSQLDatabaseService_Select_Call) RunAndReturn(run func(dest interface{}, query string, args ...interface{}) error) *MockSQLDatabaseService_Select_Call {
	_c.Call.Return(run)
	return _c
}
