// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package backend

import (
	"ce-progress-tracker/database/mssql"

	mock "github.com/stretchr/testify/mock"
)

// NewMockParticipantCourseRepositoryInterface creates a new instance of MockParticipantCourseRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantCourseRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantCourseRepositoryInterface {
	mock := &MockParticipantCourseRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParticipantCourseRepositoryInterface is an autogenerated mock type for the ParticipantCourseRepositoryInterface type
type MockParticipantCourseRepositoryInterface struct {
	mock.Mock
}

type MockParticipantCourseRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParticipantCourseRepositoryInterface) EXPECT() *MockParticipantCourseRepositoryInterface_Expecter {
	return &MockParticipantCourseRepositoryInterface_Expecter{mock: &_m.Mock}
}

// UpsertAll provides a mock function for the type MockParticipantCourseRepositoryInterface
func (_mock *MockParticipantCourseRepositoryInterface) UpsertAll(entries *[]mssql.ParticipantCourse, insertedCount *int, updatedCount *int) error {
	ret := _mock.Called(entries, insertedCount, updatedCount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]mssql.ParticipantCourse, *int, *int) error); ok {
		r0 = returnFunc(entries, insertedCount, updatedCount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParticipantCourseRepositoryInterface_UpsertAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAll'
type MockParticipantCourseRepositoryInterface_UpsertAll_Call struct {
	*mock.Call
}

// UpsertAll is a helper method to define mock.On call
//   - entries *[]models.ParticipantCourse
//   - insertedCount *int
//   - updatedCount *int
func (_e *MockParticipantCourseRepositoryInterface_Expecter) UpsertAll(entries interface{}, insertedCount interface{}, updatedCount interface{}) *MockParticipantCourseRepositoryInterface_UpsertAll_Call {
	return &MockParticipantCourseRepositoryInterface_UpsertAll_Call{Call: _e.mock.On("UpsertAll", entries, insertedCount, updatedCount)}
}

func (_c *MockParticipantCourseRepositoryInterface_UpsertAll_Call) Run(run func(entries *[]mssql.ParticipantCourse, insertedCount *int, updatedCount *int)) *MockParticipantCourseRepositoryInterface_UpsertAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *[]mssql.ParticipantCourse
		if args[0] != nil {
			arg0 = args[0].(*[]mssql.ParticipantCourse)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockParticipantCourseRepositoryInterface_UpsertAll_Call) Return(err error) *MockParticipantCourseRepositoryInterface_UpsertAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParticipantCourseRepositoryInterface_UpsertAll_Call) RunAndReturn(run func(entries *[]mssql.ParticipantCourse, insertedCount *int, updatedCount *int) error) *MockParticipantCourseRepositoryInterface_UpsertAll_Call {
	_c.Call.Return(run)
	return _c
}
