// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongo

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/mongo"
)

// NewMockDbServiceInterface creates a new instance of MockDbServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDbServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDbServiceInterface {
	mock := &MockDbServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDbServiceInterface is an autogenerated mock type for the DbServiceInterface type
type MockDbServiceInterface struct {
	mock.Mock
}

type MockDbServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDbServiceInterface) EXPECT() *MockDbServiceInterface_Expecter {
	return &MockDbServiceInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDbServiceInterface
func (_mock *MockDbServiceInterface) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDbServiceInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDbServiceInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDbServiceInterface_Expecter) Close(ctx interface{}) *MockDbServiceInterface_Close_Call {
	return &MockDbServiceInterface_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockDbServiceInterface_Close_Call) Run(run func(ctx context.Context)) *MockDbServiceInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDbServiceInterface_Close_Call) Return(err error) *MockDbServiceInterface_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDbServiceInterface_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockDbServiceInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollection provides a mock function for the type MockDbServiceInterface
func (_mock *MockDbServiceInterface) GetCollection(name string) *mongo.Collection {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 *mongo.Collection
	if returnFunc, ok := ret.Get(0).(func(string) *mongo.Collection); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Collection)
		}
	}
	return r0
}

// MockDbServiceInterface_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockDbServiceInterface_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
//   - name string
func (_e *MockDbServiceInterface_Expecter) GetCollection(name interface{}) *MockDbServiceInterface_GetCollection_Call {
	return &MockDbServiceInterface_GetCollection_Call{Call: _e.mock.On("GetCollection", name)}
}

func (_c *MockDbServiceInterface_GetCollection_Call) Run(run func(name string)) *MockDbServiceInterface_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDbServiceInterface_GetCollection_Call) Return(collection *mongo.Collection) *MockDbServiceInterface_GetCollection_Call {
	_c.Call.Return(collection)
	return _c
}

func (_c *MockDbServiceInterface_GetCollection_Call) RunAndReturn(run func(name string) *mongo.Collection) *MockDbServiceInterface_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTakesAnonymizedRepositoryInterface creates a new instance of MockTakesAnonymizedRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTakesAnonymizedRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTakesAnonymizedRepositoryInterface {
	mock := &MockTakesAnonymizedRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTakesAnonymizedRepositoryInterface is an autogenerated mock type for the TakesAnonymizedRepositoryInterface type
type MockTakesAnonymizedRepositoryInterface struct {
	mock.Mock
}

type MockTakesAnonymizedRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTakesAnonymizedRepositoryInterface) EXPECT() *MockTakesAnonymizedRepositoryInterface_Expecter {
	return &MockTakesAnonymizedRepositoryInterface_Expecter{mock: &_m.Mock}
}

// GetCourseIDCursor provides a mock function for the type MockTakesAnonymizedRepositoryInterface
func (_mock *MockTakesAnonymizedRepositoryInterface) GetCourseIDCursor(ctx context.Context, courseIDs *[]int, batchSize int) (*mongo.Cursor, error) {
	ret := _mock.Called(ctx, courseIDs, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseIDCursor")
	}

	var r0 *mongo.Cursor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, int) (*mongo.Cursor, error)); ok {
		return returnFunc(ctx, courseIDs, batchSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]int, int) *mongo.Cursor); ok {
		r0 = returnFunc(ctx, courseIDs, batchSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Cursor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]int, int) error); ok {
		r1 = returnFunc(ctx, courseIDs, batchSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourseIDCursor'
type MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call struct {
	*mock.Call
}

// GetCourseIDCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - courseIDs *[]int
//   - batchSize int
func (_e *MockTakesAnonymizedRepositoryInterface_Expecter) GetCourseIDCursor(ctx interface{}, courseIDs interface{}, batchSize interface{}) *MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call {
	return &MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call{Call: _e.mock.On("GetCourseIDCursor", ctx, courseIDs, batchSize)}
}

func (_c *MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call) Run(run func(ctx context.Context, courseIDs *[]int, batchSize int)) *MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]int
		if args[1] != nil {
			arg1 = args[1].(*[]int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call) Return(cursor *mongo.Cursor, err error) *MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call {
	_c.Call.Return(cursor, err)
	return _c
}

func (_c *MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call) RunAndReturn(run func(ctx context.Context, courseIDs *[]int, batchSize int) (*mongo.Cursor, error)) *MockTakesAnonymizedRepositoryInterface_GetCourseIDCursor_Call {
	_c.Call.Return(run)
	return _c
}
