// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mssql

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockParticipantCourseRepositoryInterface creates a new instance of MockParticipantCourseRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantCourseRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantCourseRepositoryInterface {
	mock := &MockParticipantCourseRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParticipantCourseRepositoryInterface is an autogenerated mock type for the ParticipantCourseRepositoryInterface type
type MockParticipantCourseRepositoryInterface struct {
	mock.Mock
}

type MockParticipantCourseRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParticipantCourseRepositoryInterface) EXPECT() *MockParticipantCourseRepositoryInterface_Expecter {
	return &MockParticipantCourseRepositoryInterface_Expecter{mock: &_m.Mock}
}

// UpsertAll provides a mock function for the type MockParticipantCourseRepositoryInterface
func (_mock *MockParticipantCourseRepositoryInterface) UpsertAll(entries *[]ParticipantCourse, insertedCount *int, updatedCount *int) error {
	ret := _mock.Called(entries, insertedCount, updatedCount)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]ParticipantCourse, *int, *int) error); ok {
		r0 = returnFunc(entries, insertedCount, updatedCount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParticipantCourseRepositoryInterface_UpsertAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAll'
type MockParticipantCourseRepositoryInterface_UpsertAll_Call struct {
	*mock.Call
}

// UpsertAll is a helper method to define mock.On call
//   - entries *[]ParticipantCourse
//   - insertedCount *int
//   - updatedCount *int
func (_e *MockParticipantCourseRepositoryInterface_Expecter) UpsertAll(entries interface{}, insertedCount interface{}, updatedCount interface{}) *MockParticipantCourseRepositoryInterface_UpsertAll_Call {
	return &MockParticipantCourseRepositoryInterface_UpsertAll_Call{Call: _e.mock.On("UpsertAll", entries, insertedCount, updatedCount)}
}

func (_c *MockParticipantCourseRepositoryInterface_UpsertAll_Call) Run(run func(entries *[]ParticipantCourse, insertedCount *int, updatedCount *int)) *MockParticipantCourseRepositoryInterface_UpsertAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *[]ParticipantCourse
		if args[0] != nil {
			arg0 = args[0].(*[]ParticipantCourse)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockParticipantCourseRepositoryInterface_UpsertAll_Call) Return(err error) *MockParticipantCourseRepositoryInterface_UpsertAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParticipantCourseRepositoryInterface_UpsertAll_Call) RunAndReturn(run func(entries *[]ParticipantCourse, insertedCount *int, updatedCount *int) error) *MockParticipantCourseRepositoryInterface_UpsertAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBServiceInterface creates a new instance of MockDBServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBServiceInterface {
	mock := &MockDBServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDBServiceInterface is an autogenerated mock type for the DBServiceInterface type
type MockDBServiceInterface struct {
	mock.Mock
}

type MockDBServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBServiceInterface) EXPECT() *MockDBServiceInterface_Expecter {
	return &MockDBServiceInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDBServiceInterface
func (_mock *MockDBServiceInterface) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDBServiceInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDBServiceInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDBServiceInterface_Expecter) Close() *MockDBServiceInterface_Close_Call {
	return &MockDBServiceInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDBServiceInterface_Close_Call) Run(run func()) *MockDBServiceInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBServiceInterface_Close_Call) Return(err error) *MockDBServiceInterface_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDBServiceInterface_Close_Call) RunAndReturn(run func() error) *MockDBServiceInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Rebind provides a mock function for the type MockDBServiceInterface
func (_mock *MockDBServiceInterface) Rebind(query string) string {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Rebind")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(query)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDBServiceInterface_Rebind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rebind'
type MockDBServiceInterface_Rebind_Call struct {
	*mock.Call
}

// Rebind is a helper method to define mock.On call
//   - query string
func (_e *MockDBServiceInterface_Expecter) Rebind(query interface{}) *MockDBServiceInterface_Rebind_Call {
	return &MockDBServiceInterface_Rebind_Call{Call: _e.mock.On("Rebind", query)}
}

func (_c *MockDBServiceInterface_Rebind_Call) Run(run func(query string)) *MockDBServiceInterface_Rebind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDBServiceInterface_Rebind_Call) Return(s string) *MockDBServiceInterface_Rebind_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDBServiceInterface_Rebind_Call) RunAndReturn(run func(query string) string) *MockDBServiceInterface_Rebind_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function for the type MockDBServiceInterface
func (_mock *MockDBServiceInterface) Select(dest interface{}, query string, args ...interface{}) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(dest, query, args)
	} else {
		tmpRet = _mock.Called(dest, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, string, ...interface{}) error); ok {
		r0 = returnFunc(dest, query, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDBServiceInterface_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockDBServiceInterface_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - dest interface{}
//   - query string
//   - args ...interface{}
func (_e *MockDBServiceInterface_Expecter) Select(dest interface{}, query interface{}, args ...interface{}) *MockDBServiceInterface_Select_Call {
	return &MockDBServiceInterface_Select_Call{Call: _e.mock.On("Select",
		append([]interface{}{dest, query}, args...)...)}
}

func (_c *MockDBServiceInterface_Select_Call) Run(run func(dest interface{}, query string, args ...interface{})) *MockDBServiceInterface_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDBServiceInterface_Select_Call) Return(err error) *MockDBServiceInterface_Select_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDBServiceInterface_Select_Call) RunAndReturn(run func(dest interface{}, query string, args ...interface{}) error) *MockDBServiceInterface_Select_Call {
	_c.Call.Return(run)
	return _c
}
