// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"ce-progress-tracker/internal/database/mongo"
	"ce-progress-tracker/internal/database/mssql"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDataMigrationStrategyInterface creates a new instance of MockDataMigrationStrategyInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDataMigrationStrategyInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDataMigrationStrategyInterface {
	mock := &MockDataMigrationStrategyInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDataMigrationStrategyInterface is an autogenerated mock type for the DataMigrationStrategyInterface type
type MockDataMigrationStrategyInterface struct {
	mock.Mock
}

type MockDataMigrationStrategyInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataMigrationStrategyInterface) EXPECT() *MockDataMigrationStrategyInterface_Expecter {
	return &MockDataMigrationStrategyInterface_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockDataMigrationStrategyInterface
func (_mock *MockDataMigrationStrategyInterface) Execute(ctx context.Context) (int, int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 int
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) int); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDataMigrationStrategyInterface_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDataMigrationStrategyInterface_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDataMigrationStrategyInterface_Expecter) Execute(ctx interface{}) *MockDataMigrationStrategyInterface_Execute_Call {
	return &MockDataMigrationStrategyInterface_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockDataMigrationStrategyInterface_Execute_Call) Run(run func(ctx context.Context)) *MockDataMigrationStrategyInterface_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDataMigrationStrategyInterface_Execute_Call) Return(n int, n1 int, err error) *MockDataMigrationStrategyInterface_Execute_Call {
	_c.Call.Return(n, n1, err)
	return _c
}

func (_c *MockDataMigrationStrategyInterface_Execute_Call) RunAndReturn(run func(ctx context.Context) (int, int, error)) *MockDataMigrationStrategyInterface_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParticipantMapperInterface creates a new instance of MockParticipantMapperInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantMapperInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantMapperInterface {
	mock := &MockParticipantMapperInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParticipantMapperInterface is an autogenerated mock type for the ParticipantMapperInterface type
type MockParticipantMapperInterface struct {
	mock.Mock
}

type MockParticipantMapperInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParticipantMapperInterface) EXPECT() *MockParticipantMapperInterface_Expecter {
	return &MockParticipantMapperInterface_Expecter{mock: &_m.Mock}
}

// MongoToSQL provides a mock function for the type MockParticipantMapperInterface
func (_mock *MockParticipantMapperInterface) MongoToSQL(record *mongo.TakesAnonymized) *mssql.ParticipantCourse {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for MongoToSQL")
	}

	var r0 *mssql.ParticipantCourse
	if returnFunc, ok := ret.Get(0).(func(*mongo.TakesAnonymized) *mssql.ParticipantCourse); ok {
		r0 = returnFunc(record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mssql.ParticipantCourse)
		}
	}
	return r0
}

// MockParticipantMapperInterface_MongoToSQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MongoToSQL'
type MockParticipantMapperInterface_MongoToSQL_Call struct {
	*mock.Call
}

// MongoToSQL is a helper method to define mock.On call
//   - record *mongo.TakesAnonymized
func (_e *MockParticipantMapperInterface_Expecter) MongoToSQL(record interface{}) *MockParticipantMapperInterface_MongoToSQL_Call {
	return &MockParticipantMapperInterface_MongoToSQL_Call{Call: _e.mock.On("MongoToSQL", record)}
}

func (_c *MockParticipantMapperInterface_MongoToSQL_Call) Run(run func(record *mongo.TakesAnonymized)) *MockParticipantMapperInterface_MongoToSQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mongo.TakesAnonymized
		if args[0] != nil {
			arg0 = args[0].(*mongo.TakesAnonymized)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParticipantMapperInterface_MongoToSQL_Call) Return(participantCourse *mssql.ParticipantCourse) *MockParticipantMapperInterface_MongoToSQL_Call {
	_c.Call.Return(participantCourse)
	return _c
}

func (_c *MockParticipantMapperInterface_MongoToSQL_Call) RunAndReturn(run func(record *mongo.TakesAnonymized) *mssql.ParticipantCourse) *MockParticipantMapperInterface_MongoToSQL_Call {
	_c.Call.Return(run)
	return _c
}
